version: '3'
services:
    dws-example-project:  # Will always attach to first service defined
        image: dws-example-project:latest
        build: .
        ports:
            - "8888:8888"  # jupyter default
        working_dir: /root/
        stdin_open: true
        tty: true
        command: /bin/bash
        volumes:  # home directory persisted in volume
          - homevolume:/root/
volumes:
    homevolume: {}
